name: Go Code Scanning

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-security:
    name: Lint and Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          args: "--new-from-rev=origin/main --disable=unused --timeout=10m"
        continue-on-error: true

      - name: Run GoSec Security Scan
        uses: securego/gosec@master
        with:
          args: "-exclude-generated -fmt=sarif -out=gosec_report.sarif -stdout -verbose=text ./..."
        continue-on-error: true

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec_report.sarif
