name: Go Code Scanning

on:
  pull_request:
    branches: [master]

jobs:
  lint-and-security:
    name: Lint and Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod tidy

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

      - name: Run GoSec Security Scan
        uses: securego/gosec@master
        with:
          args: ./...
